// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-0KCyqsgmy6DtCZ1XLZV11zDtxBxSaP0',
    appId: '1:734436233244:web:19e12d12a5b3f19819cfd9',
    messagingSenderId: '734436233244',
    projectId: 'fashion-store-af24f',
    authDomain: 'fashion-store-af24f.firebaseapp.com',
    storageBucket: 'fashion-store-af24f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3foFoZUq_G6b2LVQPgrU_IQJKF4aFfhU',
    appId: '1:734436233244:android:b3766bfc10aa9cda19cfd9',
    messagingSenderId: '734436233244',
    projectId: 'fashion-store-af24f',
    storageBucket: 'fashion-store-af24f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoUu5sCsA8gR8cI3wu2qe3UVlsv5WbrRg',
    appId: '1:734436233244:ios:6899e57065f2e0ee19cfd9',
    messagingSenderId: '734436233244',
    projectId: 'fashion-store-af24f',
    storageBucket: 'fashion-store-af24f.firebasestorage.app',
    iosBundleId: 'com.cit211.fashionStore',
  );
}
